### ISSUE TITLE
Not compatible with Django 5.1.3

### ISSUE THREAD

**Issue by piranna** [pikhovkin/django-schema-viewer#1]
At https://github.com/pikhovkin/django-schema-viewer/blob/e0eec9abe28fe83b4dd1ff7950025d5efa966dc5/pyproject.toml#L49 is defined a constraint of being compatible only with Django 5.0.x, not with Django 5.1.0 or higher, so it's not possible to install the project with recent Django versions.

**Comment by pikhovkin** [comment]
done
